name: CI/CD Pipeline Java com H2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    name: Build & Test com Java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build e Testes com Maven
        run: ./mvnw -B verify

      - name: Publicar JAR como artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
